### ISSUE TITLE
Activating auto-layout causes click-lag 

### ISSUE THREAD

**Issue by Toinman** [AnimaApp/Auto-Layout#100]
Once I activate the auto-layout Sketch become slow and has click-lag on several places.

Most notably, selecting layers becomes frustratingly laggy. 

I made a video (below). Pay attention to the delay between clicking the layers, and the layers being selected in the layer list. It may look subtle, but it's a real blocking issue when working 24/7 in Sketch. Also, it tend to get worse in larges documents. 

https://drive.google.com/file/d/1WDxtVg22a29k5x2ElEdiaZUd7aGvchWl/view?usp=sharing

**Comment by avishic** [comment]
Thanks @Toinman for the report!
It was a dark mode issue, fixed on the [latest release](https://www.animaapp.com/download/launchpad) from a few minutes ago.

- Restart Sketch after install
