### ISSUE TITLE
Feature request: selective padding

### ISSUE THREAD

**Issue by Slaaavo** [AnimaApp/Auto-Layout#106]
Right now, padding is useful only for making components that should adapt to its content completely. It would be great if I could specify, whether padding should be applied in all directions, or just vertically or just horizontally. Say I want a paragraph with a padding and I want to be able to resize horizontally for different screen sizes. Right now, that doesn't work, so I can't use padding, even though it would be great application for this feature.

**Comment by Slaaavo** [comment]
This is a duplicate of Padding in symbol make it Fixed size? #105

**Comment by Spodesnl** [comment]
I was looking for the "fixed size" issue and came across your post and #105. I found a way to make this work. When you create the padding group, it works fine. The moment you click the padding group, it becomes fixed. If you click the "fix size" again, making it unfixed and then never touch the padding group again, it seems to stay unfixed. You can then resize it horizontally and then the will adapt to the amount of text.

So if touch any layer in the paddinggroup, make the size unfixed again and it should work fine...
