### ISSUE TITLE
Auto Layout while rotate Text

### ISSUE THREAD

**Issue by Nevu** [AnimaApp/Auto-Layout#14]
Am I wrong or goes the Auto-Layout-Crazy when trying to pin rotatet text? (f.e. 90° pin left)

![goingcrazy](https://cloud.githubusercontent.com/assets/2456068/22102925/7f308d90-de39-11e6-9a5d-dbbf769ee543.png)

**Comment by orarbel** [comment]
@Nevu I tried to reproduce on version 0.1.2 and couldn't. can you try updating and let us know if the problem still exists?

If it does can you attach a Sketch file?

**Comment by Nevu** [comment]
hello orarbel!

I tried to reproduced in a new document, also tried to do some similar. Everything seems to be fixed (maybe since the latest update?!). Thank you and sorry that I didn't give an update before!
