### ISSUE TITLE
Feature to use any layer as container, not just artboard

### ISSUE THREAD

**Issue by andrewnenakhov** [AnimaApp/Auto-Layout#15]
That'd make this plugin even more insanely great than it already is. It'll make possible to create resizable cards within one artboard.

**Comment by orarbel** [comment]
Hi @andrewnenakhov, if a layer is inside a group, the pins are relative to the group and not the artboard.

Does this help?

**Comment by orarbel** [comment]
https://animaapp.github.io/docs/v1/guide/03-pins.html#Pin-to-Parent

**Comment by andrewnenakhov** [comment]
Yes, it does help, thanks. Didnt' find that docs, sorry.

**Comment by orarbel** [comment]
The docs are brand new, launched today :)
