### ISSUE TITLE
textwitdh is broken

### ISSUE THREAD

**Issue by edwardbiz** [AnimaApp/Auto-Layout#17]
Without the plugin when I create a text layer on sketch I can change the width of the text layer
When the plugin is installed and I create a text layer then I can resize the width anymore.

Here is the video of the issue
[textwidth-broken.mp4.zip](https://github.com/AnimaApp/Auto-Layout/files/742801/textwidth-broken.mp4.zip)

**Comment by orarbel** [comment]
Fixed and released in 0.1.4 Thanks!

**Comment by edwardbiz** [comment]
nice thanks !
