### ISSUE TITLE
Constraint to other layers

### ISSUE THREAD

**Issue by markst** [AnimaApp/Auto-Layout#19]
Something we use most in Interface Builder is being able to constraint to other views just like this:
![http://d.pr/i/wbmP](http://d.pr/i/wbmP.gif)

**Comment by orarbel** [comment]
Hi @markst! our next release has this with a new feature called Stacks.

Stacks:
- Define constraints between sibling layers.
- Push sibling layers when Text expands.
- Can be nested.
- Support Vertical or Horizontal layout.
- Respect Ratio-Lock.
- Are easily setup with one click.

https://youtu.be/QUtCDyBVG_s

Here it is http://bit.ly/2lu2vKM (Restart Sketch after install)

**Comment by orarbel** [comment]
Stacks has been released 🙂
