### ISSUE TITLE
Images in help bubble are broken

### ISSUE THREAD

**Issue by chriscalo** [AnimaApp/Auto-Layout#34]
Images in the help bubble don't display.

![anima app help bubble](https://cloud.githubusercontent.com/assets/867717/24364731/ae4bd5da-12e1-11e7-9007-be0a577b1276.gif)

![image](https://cloud.githubusercontent.com/assets/867717/24364768/cbb03bb6-12e1-11e7-95d1-351b7be1acdf.png)

**Comment by orarbel** [comment]
Fixed in 0.3.15 👍
