### ISSUE TITLE
[bug] switching devices doesn't respect orientation

### ISSUE THREAD

**Issue by RaphyRaph** [AnimaApp/Auto-Layout#4]
when you have an dartboard in landscape and switch to another device, it defaults to portrait.

![bitmap](https://cloud.githubusercontent.com/assets/3810802/21646207/18096784-d28d-11e6-9221-5c1bbb5e1f13.png)

**Comment by avishic** [comment]
Fixed on 0.1.1 (Release around Sunday Jan-15)
