### ISSUE TITLE
'What's New' Command Shows Empty Change Log Window, Wrong Version Number

### ISSUE THREAD

**Issue by luxlogica** [AnimaApp/Auto-Layout#41]
In version 0.5.0, selecting _"Plugins -> LaunchPad by Anima -> Version -> What's New"_ produces the following window:

<img width="607" alt="screen shot 2017-05-03 at 9 16 52 am" src="https://cloud.githubusercontent.com/assets/2994472/25643351/a5b9b6da-2fe2-11e7-9813-c3a42383288d.png">

I'm guessing that considering the plugin is now at version 0.5.0, there should be *something* in the change log - and also, that it perhaps shouldn't tell me that I'm on version 0.0.3...

**Comment by luxlogica** [comment]
I have just downloaded the '**Launchpad**' plugin, directly from the [official Launchpad page], and it does not cause this issue. 

If the plugin is installed as the '**Auto-Layout**' plugin - via either [Sketchpacks](https://sketchpacks.com) or the newer [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/), then we end up with a buggy version that presents the error reported here.

It seems *"Auto-Layout v0.5.2"* and *"Launchpad v0.5.2"* are not the same plugin: the 'auto-layout' version is buggy, and that is unfortunately the version that the plugin managers are installing automatically.

Explained in issue #47.

**Comment by orarbel** [comment]
Fixed!
