### ISSUE TITLE
Auto-Layout Disclosure Triangle in Wrong Position in New Windows

### ISSUE THREAD

**Issue by luxlogica** [AnimaApp/Auto-Layout#42]
When opening a document window, the Anima Panel defaults to open, with both LaunchPad and the Auto-Layout showing. The Auto-Layout panel is fully open - showing all advanced options - but its disclosure triangle is in the 'closed' position:

<img width="270" alt="screen shot 2017-05-03 at 9 15 08 am" src="https://cloud.githubusercontent.com/assets/2994472/25643574/e5cc9db8-2fe3-11e7-818f-3c185e2d68ee.png">

Toggling the Anima Panel - and forcing a redraw - seems to fix it.

**Comment by luxlogica** [comment]
I have just downloaded the '**Launchpad**' plugin, directly from the [official Launchpad page], and it does not cause this issue. 

If the plugin is installed as the '**Auto-Layout**' plugin - via either [Sketchpacks](https://sketchpacks.com) or the newer [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/), then we end up with a buggy version that presents the error reported here.

It seems *"Auto-Layout v0.5.2"* and *"Launchpad v0.5.2"* are not the same plugin: the 'auto-layout' version is buggy, and that is unfortunately the version that the plugin managers are installing automatically.

Explained in issue #47.

**Comment by orarbel** [comment]
Fixed!
