### ISSUE TITLE
Anima Panel Should Auto-Resize and Only Take Up Required Space

### ISSUE THREAD

**Issue by luxlogica** [AnimaApp/Auto-Layout#43]
The new Anima Panel takes up over 50% of the Inspector, **always** - regardless of whether it needs it or not:

<img width="215" alt="screen shot 2017-05-03 at 9 17 59 am" src="https://cloud.githubusercontent.com/assets/2994472/25643814/217e798e-2fe5-11e7-9abb-2a2208a9f073.png">

The expected behaviour would be that the panel should resize itself and move out of the way, as required - and not obtrusively impose itself over the Sketch panels whenever it's on-screen, even when it's taking up space that is obviously not required. This behaviour forces the user to continuously toggle the panel *off* in order to work...

**Comment by luxlogica** [comment]
I have just downloaded the '**Launchpad**' plugin, directly from the [official Launchpad page], and it does not cause this issue. 

If the plugin is installed as the '**Auto-Layout**' plugin - via either [Sketchpacks](https://sketchpacks.com) or the newer [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/), then we end up with a buggy version that presents the error reported here.

It seems *"Auto-Layout v0.5.2"* and *"Launchpad v0.5.2"* are not the same plugin: the 'auto-layout' version is buggy, and that is unfortunately the version that the plugin managers are installing automatically.

Explained in issue #47.

**Comment by orarbel** [comment]
Fixed!
