### ISSUE TITLE
Anima Panel Shows Redraw Glitch When Opening New Doc Window

### ISSUE THREAD

**Issue by luxlogica** [AnimaApp/Auto-Layout#44]
## Steps to Reproduce
1. Open an existing Sketch document - it will open with the Anima Panel already showing
2. While leaving the document window open, open a second document.

## Result
The Anima Panel shows an ugly redraw issue in the second document window - it seems the 'Inner Shadow' and 'Gaussian Blur' panel titles are drawn over Anima Panel's:

<img width="211" alt="screen shot 2017-05-03 at 9 21 45 am" src="https://cloud.githubusercontent.com/assets/2994472/25643934/fb270962-2fe5-11e7-8812-4de925649a36.png">

## Workaround
Doing anything that forces a screen redraw - eg., clicking in one of the Inspector panels - fixes the glitch.

**Comment by orarbel** [comment]
Thanks for all the issue reports 🙏. Can you confirm that Sketch has been restarted since installing 0.5.0?

**Comment by luxlogica** [comment]
@orarbel - indeed, I have restarted it several times. The issue is reproducible. 

The plugin was installed via Sketchpacks - don't know whether it's relevant?...

**Comment by luxlogica** [comment]
I have just downloaded the '**Launchpad**' plugin, directly from the [official Launchpad page], and it does not cause this issue. 

If the plugin is installed as the '**Auto-Layout**' plugin - via either [Sketchpacks](https://sketchpacks.com) or the newer [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/), then we end up with a buggy version that presents the error reported here.

It seems *"Auto-Layout v0.5.2"* and *"Launchpad v0.5.2"* are not the same plugin: the 'auto-layout' version is buggy, and that is unfortunately the version that the plugin managers are installing automatically.

Explained in issue #47.

**Comment by orarbel** [comment]
Fixed!
