### ISSUE TITLE
[BUG] Some Anima Panel Menu Commands Crash Sketch

### ISSUE THREAD

**Issue by luxlogica** [AnimaApp/Auto-Layout#45]
## Steps to Reproduce
1. Open an existing Sketch document. It will open with the Anima Panel already on the Inspector.
2. Open the menu in the Anima Panel itself (by clicking the cog icon), and select one of these commands: "Sites Manager", "Send Feedback" or "My Account".

## Result
Sketch crashes and quits - with a crash report window coming up.

I have not signed up for the LaunchPad service, so cannot tell whether having a LaunchPad account would make a difference.

**Comment by luxlogica** [comment]
I have just downloaded the '**Launchpad**' plugin, directly from the [official Launchpad page], and it does not cause this issue. Using one of the Sketch plugin managers to instal the plugin, however, 

If the plugin is installed - as the '**Auto-Layout**' plugin - via either [Sketchpacks](https://sketchpacks.com) or the newer [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/), then we end up with a buggy version that presents the error reported here.

It seems *"Auto-Layout v0.5.2"* and *"Launchpad v0.5.2"* are not the same plugin: the 'auto-layout' version is buggy, and that is unfortunately the version that the plugin managers are installing automatically.

**Comment by orarbel** [comment]
Fixed!
