### ISSUE TITLE
Version Installed by Plugin Managers is Buggy

### ISSUE THREAD

**Issue by luxlogica** [AnimaApp/Auto-Layout#47]
Today I came across the [Launchpad official page](https://launchpad.animaapp.com), and decided to manually install the plugin, instead of using one of the current plugin managers. Much to my surprise, after having reported several bugs here, the Launchpad plugin simply worked as advertised - no bugs at all!

So, I uninstalled it, and tried re-installing it using the 2 newest plugin managers: [Sketchpacks](https://sketchpacks.com) and [Sketch Plugin Manager](https://mludowise.github.io/Sketch-Plugin-Manager/). Both managers allow me to instal (supposedly) version 0.5.2 of 'Auto-Layout' - which supposedly should be *the same plugin* as 'Launchpad' (considering they both have the same version number and exactly the same feature set). However, installing 'Auto-Layout' via either one of the plugin managers installs the **very buggy version** reported previously. Downloading and installing 'Launchpad' manually, directly from its official page, instals a bug-free version.

It seems, therefore, that the plugin managers are installing a different version of the plugin, which needs to be updated with all the corrections already available in the official 'Launchpad' 0.5.2. 

Please note also, that after installing Launchpad manually, if the user has one of the plugin managers installed, it will detect Launchpad as being an *older* version of 'Auto-Layout', and will try to update it - Sketch Plugin Manager does this every time you launch Sketch. Needless to say, if the user 'updates' the plugin, they will get the buggy version...

This affects issues #41, #42, #43, #44 and #45.

**Comment by orarbel** [comment]
Oh my, thank you so much.

We've pushed a fix. Seems like it should work now.
