### ISSUE TITLE
[Feature] Distance from next object + layout defaults for object collections

### ISSUE THREAD

**Issue by orarbel** [AnimaApp/Auto-Layout#6]
https://github.com/AnimaApp/AnimaApp/issues/1 @salux

**Comment by RaphyRaph** [comment]
As noted earlier, the way subform handles it is quite nice. https://subformapp.com/learn/layout/ I think in general it's important to mirror the layout logic of flexbox, because production will most likely be implemented that way.

**Comment by avishic** [comment]
Thanks @RaphyRaph !
That's a great suggestion, I'm adding it to our wishlist & keeping it open here

**Comment by orarbel** [comment]
https://medium.com/sketch-app-sources/auto-layout-introducing-stacks-flexbox-for-sketch-c8a11422c7b5
