### ISSUE TITLE
[Feature Request] Allow device scale to be editable

### ISSUE THREAD

**Issue by petebarr** [AnimaApp/Auto-Layout#60]
I've been looking through the plugin to see if I can change the scale of say the iOS layouts to @1x rather than the default @2x. If this is possible would you be so kind as to show me where? It's generally accepted to design in Sketch @1x: https://medium.com/shyp-design/design-at-1x-its-a-fact-249c5b896536

**Comment by orarbel** [comment]
Thanks for the request @petebarr. 

Today you can create a presets json file and specify the scale. 

Please check out https://github.com/AnimaApp/Auto-Layout/tree/master/presets

**Comment by petebarr** [comment]
Thanks. Where is that located when installed?

**Comment by orarbel** [comment]
The default presets are hard-coded in the plugin so they are not available as plain text.

You can create a new custom preset collection like this one: https://github.com/AnimaApp/Auto-Layout/blob/master/presets/files/AutoLayoutPresets.json

and import it

**Comment by petebarr** [comment]
Cheers, I thought that might be the case.

**Comment by orarbel** [comment]
Cheers 👍  :)
