### ISSUE TITLE
Sketch 48 - auto layout not supported in symbols

### ISSUE THREAD

**Issue by RaphyRaph** [AnimaApp/Auto-Layout#64]

**Comment by Maikenvv** [comment]
I have the same issue and it broke multiple design files. 

I often see the same issue when syncing a page with symbols with auto layout to Marvel. Maybe it is connected?

**Comment by orarbel** [comment]
Hi @RaphyRaph and @Maikenvv, this was fixed in 0.11 :)

**Comment by joevillanueva** [comment]
Let me just add that I was having issues with this, even running 0.11. It was only after removing and re-installing (I kept Sketch open while doing so) that the issue was actually fixed.

**Comment by elechaudel** [comment]
Thanks @joevillanueva, you're right.

1. Uninstall Anima App (Plugins > Manage Plugins > Select Anima App in the list and then click the wheel icon at the bottom left > and click Uninstall).
2. Quit Sketch
3. Download the last version of [Anima App](https://animaapp.github.io/)
4. Open Sketch
5. Install the Anima App Plugin
6. Quit sketch
7. Open the file where your symbols were broken

Your broken symbols should be fixed!

**Comment by AlBancher** [comment]
i have sketch 50.2 and anima tool kit and resizing is not working still .. reinstalled twice!!! Help!
