### ISSUE TITLE
Support for Sketch 49

### ISSUE THREAD

**Issue by tijmenvangurp** [AnimaApp/Auto-Layout#69]
Auto Layout is not compatible anymore with sketch 49

See below image:

![image](https://user-images.githubusercontent.com/9990026/36784391-79a06f00-1c7f-11e8-92e0-6bc971aed5b0.png)

Hope this can be solved quickly! :)

**Comment by JoeDawson** [comment]
I could update now @tijmenvangurp :)

**Comment by avishic** [comment]
Hey guys, 
Update available, but if you can't see the button in Sketch, get it here:
https://animaapp.s3.amazonaws.com/sketchplugin/launchpad/LaunchpadPlugin.zip

We'll update Github as well
@tijmenvangurp
