### ISSUE TITLE
[bug] when aligning and resizing, respect pixel-fitting rules

### ISSUE THREAD

**Issue by RaphyRaph** [AnimaApp/Auto-Layout#7]
I'm noticing a lot of decimal values when moving/resizing things. I understand the need for precision when applying percentages, but it ends up creating a complete mess of decimal values. This makes elements blurry and hard to recover, even when running the fit to pixel command. Pixel fitting, especially if explicitly turned on in Sketch settings, should supercede exact calculations in UI design.

![bitmap](https://cloud.githubusercontent.com/assets/3810802/21649461/b9769388-d299-11e6-8bee-836f7231c1c5.png)

**Comment by avishic** [comment]
Resolved on 0.1.0
