### ISSUE TITLE
Exporting for Invision (with Craft) and Zeplin has critical problems

### ISSUE THREAD

**Issue by delizade** [AnimaApp/Auto-Layout#70]
Hello everyone,

First of all huge thank you for the grate plugin that changed my design workflow totally. In currently I had to use it for a huge project. But we've been struggling to solve exporting issues for Invision and especially Zeplin. Project has currently 30 pages and we are continuing to add new designs because of the weekly delivery deadlines. 

When we tried to export, page layouts are being exported as broken/altered. Currently Anima App team is working for it we know and thanks for that but we thought that may be it was solved thanks to using some magical tricks :/ by other designers.

Do you have any solutions for that?

thank you.

**Comment by orarbel** [comment]
Hi @delizade, can you upload a Sketch file that has the issue? 

Is it only in Stacks? or also pins?

**Comment by orangefult** [comment]
I'm experiencing this as well. I think it happens when more than on symbol at a time is detached. If you do it one at a time it seems to work alright.

So... although it will be a pain in the rear, you could manually go through and detatch all your symbols one at a time, then upload to Invision/Zepplin, and then use cmd-z like crazy.

![one at a time symbol detatch](https://user-images.githubusercontent.com/2236632/37169361-f2ee91f2-22c4-11e8-93b6-bc044a868070.gif)
![all at once symbols detatch](https://user-images.githubusercontent.com/2236632/37169362-f304247c-22c4-11e8-8146-a4000829d5c5.gif)

**Comment by avishic** [comment]
Hey guys! 
Until we fix the multiple selection:

Select your artboards, use detach recursive, screenshot attached.
It will detach everything in 1 action-> Single undo :)

<img width="881" alt="screen shot 2018-03-11 at 9 09 08" src="https://user-images.githubusercontent.com/4908786/37250788-ba743634-250c-11e8-9299-9faa003ef662.png">

**Comment by delizade** [comment]
Hi everyone,
@orarbel Sorry because of our fully dedicated working days I couldnt share documents here. 
@orangefult thank you. unfortunately that way may work for small projects but we can not use it.

@avishic I think we tried it but not sure I will try it to see result to be clear. thank you so much. 

I will tey to share as much as detailed cases. I hıpe we can solve this before development delivery. And we have a huge horror about that phase for now:/

**Comment by avishic** [comment]
@delizade @orangefult 
Until the official release here's the patch fix: 

https://cl.ly/1O3K3q2e1C0q
- Restart Sketch after install

**Comment by delizade** [comment]
Hi,
Thank you for your efforts.
I tested it new ver. but unfortunately it cant be done as recursively and same issues we have. I tried detach recursively

thank you again

![detach](https://user-images.githubusercontent.com/727548/37287716-5d061b88-25fd-11e8-8bf5-3914df5bc9ff.png)
[Test-DetachSymbols.sketch.zip](https://github.com/AnimaApp/Auto-Layout/files/1803018/Test-DetachSymbols.sketch.zip)

**Comment by avishic** [comment]
Thanks @delizade !
We'll fix it too, the case here is that the stack is the only item in the symbol.
**Workaround**: group the stack in the symbol (screenshot)

<img width="493" alt="screen shot 2018-03-12 at 22 41 21" src="https://user-images.githubusercontent.com/4908786/37308579-2bd336e6-2647-11e8-86cd-b29d7e5db66d.png">

**Comment by avishic** [comment]
@delizade it went smoother then we thought, here's the patch fix:
https://cl.ly/2B2q312U400z
- Restart Sketch 

We've also fixed "Prepare export for other plugins" option that broke on Sketch 49.
Let us know all went smooth this time :)

**Comment by delizade** [comment]
Hi @avishic
I can’t find a word for thank you. It seems okay now. I will be deep test later. Thank you so much!

**Comment by delizade** [comment]
Hi @avishic ,
I prepared a sample file to show one of my problems. It is similar problem with @chsWeb i think.


[AutoLayout-Problem.sketch.zip](https://github.com/AnimaApp/Auto-Layout/files/1841383/AutoLayout-Problem.sketch.zip)
![result 1x](https://user-images.githubusercontent.com/727548/37827882-22168d36-2e91-11e8-9a25-6782f45ec99f.png)
![source 1x](https://user-images.githubusercontent.com/727548/37827883-2232e986-2e91-11e8-846e-120aeede8024.png)

**Comment by orarbel** [comment]
@delizade I've found something similar. Can you share more about your findings regarding the Fixed/Auto Text Layers issue?

**Comment by delizade** [comment]
Sadly we’ve decided to remove auto layout groups completly from about 90 arboards. It will take a huge time but after testing latest version of autolayout we experienced minor and major many problems when using detaching or “prepare for other plugins” to send to Zeplin.

**Comment by chsWeb** [comment]
@delizade same here, have abandoned Auto Layout and shifted to Paddy.

To speed the process up, you can use the Unstack Group Short cut and the Rename layer plugin to apply Paddy in Auto layout's place.

**Comment by chsWeb** [comment]
@delizade I found that if I was using Auto Layout Pinning, it was causing problems with Craft Sync. For example, if a I have a input, made of a text symbol and a shape symbol, where the text symbol was pinned to the left edge, when syncing to InVision, the text would be cropped.

Sketch is a bit painful without Auto Layout… I do hope you are able to sort these bugs out. I do understand that it is very complicated.

**Comment by orarbel** [comment]
We are releasing a version today that has critical fixes in the "Export to other plugins" feature.

Let us know if it works for you: https://cl.ly/081l2a3f0O1y/AnimaTookitPlugin.zip

(Restart Sketch after installing)

**Comment by delizade** [comment]
@chsWeb thank you for your suggestions I will look into it.
@orarbel thank you as well when I find a time I will look new version and let you know result.

**Comment by delizade** [comment]
Hi @orarbel 
here is one of our artboard situation. We can't check all but I think sharing one of them better than nothing :) thank you.


![original 2](https://user-images.githubusercontent.com/727548/38204567-5e0c99cc-369b-11e8-954c-97dac15b4f8c.png)
![result after prepare for other plugins](https://user-images.githubusercontent.com/727548/38204568-5e2629b4-369b-11e8-8f2f-b7f616a5fc6f.png)
[test-08.sketch.zip](https://github.com/AnimaApp/Auto-Layout/files/1868586/test-08.sketch.zip)

**Comment by avishic** [comment]
@delizade thanks for the file!
With the latest beta it works for me :)

https://cl.ly/1m2R2v2i2X1w
- Restart Sketch after install

Could you make sure all work well?

**Comment by delizade** [comment]
Hi everyone!
this is a crazy news because I forgot to restart Sketch yesterday!

I did it now, I checked them and currently I want to cry, everything seems perfect!

So now, we will rearrange some artboards that we have removed plugin and we will send them to Zeplin.

@avishic thank you again!

**Comment by stigmates** [comment]
Still critical issues. Can't use autolayout anymore. Too much time loose when exporting to zeplin.

**Comment by SimonFricker** [comment]
+1 this is still an issue
