### ISSUE TITLE
SLOW & CRASHING: Stacked Groups & Editing Multiple Symbols At One Time

### ISSUE THREAD

**Issue by chsWeb** [AnimaApp/Auto-Layout#71]
**PROBLEM:**

I cannot edit multiple symbols in a stacked group without massive slowdowns or crashing in Sketch.

**EXPECTED BEHAVIOR:**

I should be able to edit multiple symbol widths or overrides at one time, by simple selecting multiple instances of a symbol, in a stacked group, and entering a new width in the Properties panel, or a new value in the Overrides panel.

**CURRENT BEHAVIOR:**

When entering a new width or override for multiple symbols at one time, Sketch crashes. Turing Auto Layout prevents the crash from happening. In fact, with multiple instances selected, simply clicking in the Properties panel to enter a new width results in the pinwheel of death, the a crash or Force Quit.

**STEPS TO REPRODUCE:**

1. Create a new symbol using a rectangle and one text layer. Add this symbol to a Sketch library
2. Insert 20 instances of the library symbols to an artboard & put them in a new horizontal stacked group with no space.
3. Duplicate the stacked group 5 times.
4. Add the 6 horizontal stacked groups into a new vertical stack group with no space.
5. Select one symbol in each horizontal group by holding SHIFT + CMD (⌘) to select multiple symbols
6. Attempt to change their width by entering a new wide value in the Properties panel OR try entering a new override value in the Override panel.

**TROUBLESHOOTING STEPS TAKEN SO FAR:**

- disable all plugins (no problems); turn auto layout back on and there are problems
- restart sketch, close all windows except for current window
- the problem seems to creep up over time, the longer I work in Sketch, the more sever the pinwheel and eventual crashing.
- restarting Sketch seems to by some time where auto layout works fine.
- after 30 minutes, the crashing begins, as if there is a memory leak or something?
- working in a less complex file, with less artboards, does seem to help, but I have not tested this over time.
- after restarting Sketch, and turning on Auto Layout, initially there is no crashing. After 20 or 30 minutes of work, the crashing returns.
- If I had to guess, I'd say there is some sort of memory leak, or a cache problem, or something to do with the private files that Sketch creates in OS X that sometimes get huge - perhaps lots of library symbols and editing creates a large private file?

**Comment by najiglass** [comment]
I'm having the same issue, I only use stacks (not pinning or sizes). At least having a way to disable auto-updating stacks would help. Sketch is barely usable when the Anima plugin is enabled.

**Comment by chsWeb** [comment]
See if Paddy for Sketch can be used in place of Auto Layout, that is what I am doing now.

[Paddy](https://github.com/DWilliames/paddy-sketch-plugin)

**Comment by najiglass** [comment]
It can’t for stacking since Paddy doesn’t work many layers deep for symbols. I would have to detach everything, which defeats the purpose.

Andrey

**Comment by chsWeb** [comment]
Does "Closed" = "Fixed?"

**Comment by najiglass** [comment]
Not fixed for me, and no alternative solution, we should re-open the issue.

**Comment by placidminds** [comment]
This is still an issue. Opening a new ticket.

**Comment by bios82** [comment]
Any news or reports they're working on this?
Combination of Sketch + Anima needs 99% of my CPU.
Really needs to be fixed.

**Comment by zetaap** [comment]
> Combination of Sketch + Anima needs 99% of my CPU.
I have the same problem :( Freezes after any action

**Comment by luclemo** [comment]
Same issue here

**Comment by nakrill** [comment]
Same issue! It feels like performance issue is not related to the general count of stacked groups or nested level, but it definitely some unpredictable behavior.
