### ISSUE TITLE
Plugin not installing?

### ISSUE THREAD

**Issue by nathangross** [AnimaApp/Auto-Layout#80]
I have had this plugin installed for quite some time. I use it extensively.

When I opened Sketch today, the plugin UI did was not visible. I tried to reinstall the plugin, remove and reinstall, remove all other plugins, restarting sketch, etc.—nothing seems to work. Are there any known issues with this current version of Auto Layout and Sketch 49.1?

A few more details:

I normally use Sketchpacks to manage most plugins. Sketchpacks shows that Auto Layout is available for install. I click to install, UI shows successful installation. No Auto Layout UI in Sketch. I go back to Sketchpacks and it says it's available for install again. 

The plugin does appear in Sketch's plugins directory.

Any ideas of what is happening here?

**Comment by chsWeb** [comment]
**UPDATE:** 
Auto Layout is back again. Not sure why, but the UI is now appearing in the Inspector Panel. Is it working for you too @nathangross?

**Comment by nathangross** [comment]
@chsWeb I still do not see any UI for Auto Layout anywhere. It seems the plugin isn't even installed. While it is in my plugins directory, it does not show up in the Plugins tab in Sketch Preferences. It also does not appear to be installed via Sketchpacks.

https://www.dropbox.com/s/c3jlglvrea0eelb/Screenshot%202018-03-21%2016.24.34.png?dl=0

**Comment by orarbel** [comment]
Hi @nathangross, have you tried to restart Sketch?

**Comment by nathangross** [comment]
> I tried to reinstall the plugin, remove and reinstall, remove all other plugins, restarting sketch, etc.—nothing seems to work.

@orarbel I did with no luck. Restarted the computer as well.

**Comment by nathangross** [comment]
Using the direct link worked! Thank you @orarbel.
