### ISSUE TITLE
Change "show/hide panel" shortcut?

### ISSUE THREAD

**Issue by dsedivec** [AnimaApp/Auto-Layout#85]
Hi!  Would you consider assigning a new shortcut to "show/hide panel"?  It seems to currently be assigned to ^A, which is not only Sketch's default shortcut for "Pin Left" but also the universal macOS shortcut for "go to beginning of line" when entering text.  Today I went to edit a text object in Sketch, hit ^A expecting my cursor to go to the beginning of the paragraph, but nothing happened—until I noticed I was toggling the Anima panel on/off repeatedly!  It was very frustrating, since ^A goes to beginning of line basically everywhere else in every application on macOS.

Thanks for your consideration, and for your awesome Sketch plug-in!

**Comment by orarbel** [comment]
Fixed in 0.13.5
