### ISSUE TITLE
[Feature] multiple selection - set pins

### ISSUE THREAD

**Issue by illustree** [AnimaApp/Auto-Layout#9]
would be cool to be able to select multiple layers and then apply the pins to all selected. thanks in advance! GREATEST PLUGIN EVER guys!

**Comment by Nevu** [comment]
I support this!

**Comment by avishic** [comment]
Great suggestion @illustree  & @Nevu !
I'm adding it to the wishlist & keeping it opened here

**Comment by orarbel** [comment]
Implemented in 0.1.2
