### ISSUE TITLE
Auto-Layout stacks vs Paddy 2 ?!

### ISSUE THREAD

**Issue by stigmates** [AnimaApp/Auto-Layout#96]
Hey,
Big dilemna this week. Have to choose between Paddy 2 (beta) and Auto-Layout! And I can't! but I have to. Paddy 2 beta offers smarter stacks with possibility to deal with dynamic groups and symbols when overriding contents while Auto-Layout can't but this one is more reliable.
Any future update to enrich stacks to deal with dynmaic buttons and stuffs like this? 
Would be great.
Thx

**Comment by nickm717** [comment]
A bit late, but Paddy 2 is no longer support in Sketch 52 and no new support is being developed.

**Comment by orarbel** [comment]
We do have plans to introduce more features to Stacks like margins and padding 💯
